;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
ManifestDependencies=../../UE_Versions/UE_5.6/Engine/Content/Localization/Engine/Engine.manifest
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
ManifestName=Game.manifest
ArchiveName=Game.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=zh-Hans

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=Plugins/GraphicSettings/Source/GraphicSettings
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Plugins/GraphicSettings/Content/StringTables/*
IncludePathFilters=Content/UI/*
IncludePathFilters=Content/Characters/*
IncludePathFilters=Content/Sounds/SoundClasses/*
IncludePathFilters=Plugins/ALS-Refactored/Content/ALS/Data/Input/*
IncludePathFilters=Plugins/InventorySystem/Content/Inputs/*
IncludePathFilters=Plugins/Minimap/Content/Inputs/*
IncludePathFilters=Content/Minimap/*
IncludePathFilters=Content/Inventory/*
IncludePathFilters=Content/FlowGraph/Quests/*
IncludePathFilters=Content/FlowGraph/Dialogues/*
IncludePathFilters=Content/FlowGraph/Nodes/*
IncludePathFilters=Content/Inputs/*
IncludePathFilters=Content/BuildingSystem/*
ExcludePathFilters=Content/Localization/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
ExcludeClasses=/Script/EnhancedInput.InputAction
ExcludeClasses=/Script/OptimusCore.OptimusDeformer
ExcludeClasses=/Script/Engine.AnimInstance
ShouldExcludeDerivedClasses=false
ShouldGatherFromEditorOnlyData=false
SkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive

[GatherTextStep4]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Game.csv
bConflictReport=true
ConflictReportName=Game_Conflicts.txt

