;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GAS.Conditions.HasOxygen",NewTagName="GAS.Conditions.Underwater")
+GameplayTagRedirects=(OldTagName="GAS.Conditions.ForceUnequip",NewTagName="GAS.Conditions.CanEquip")
+GameplayTagList=(Tag="Als.Damage.Cellien",DevComment="")
+GameplayTagList=(Tag="Als.Damage.Drown",DevComment="")
+GameplayTagList=(Tag="Character.Anchor",DevComment="")
+GameplayTagList=(Tag="Character.Cellien",DevComment="")
+GameplayTagList=(Tag="Character.Kaban",DevComment="")
+GameplayTagList=(Tag="Character.Macaw",DevComment="")
+GameplayTagList=(Tag="Character.Otter",DevComment="")
+GameplayTagList=(Tag="Character.Serval",DevComment="")
+GameplayTagList=(Tag="Character.Toki",DevComment="")
+GameplayTagList=(Tag="Character.Tsuchinoko",DevComment="")
+GameplayTagList=(Tag="Collectables.SandStar",DevComment="")
+GameplayTagList=(Tag="Data.BlockMove",DevComment="")
+GameplayTagList=(Tag="Data.FuelRate",DevComment="")
+GameplayTagList=(Tag="Data.MoveTo",DevComment="")
+GameplayTagList=(Tag="Flow.Test",DevComment="")
+GameplayTagList=(Tag="Flow.World.LakeCamera",DevComment="")
+GameplayTagList=(Tag="Flow.World.Ship.AnchorMon",DevComment="")
+GameplayTagList=(Tag="Flow.World.Ship.Clean",DevComment="")
+GameplayTagList=(Tag="Flow.World.Ship.Elect",DevComment="")
+GameplayTagList=(Tag="Flow.World.Ship.TsuRoom",DevComment="")
+GameplayTagList=(Tag="Flow.World.TopTree",DevComment="")
+GameplayTagList=(Tag="Flow.World.TopTreeCamera",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.AttackTrace",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.ChangeEquip",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.End",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.EndInteract",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.Interact",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.ItemEquiped",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.NormalAttack",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.PreInput",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.Sitting",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.Sleeping",DevComment="")
+GameplayTagList=(Tag="GAS.Abilities.Teleport",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.HpEmpty",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.HpFull",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.OxygenEmpty",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.OxygenFull",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.StaminaEmpty",DevComment="")
+GameplayTagList=(Tag="GAS.Attributes.StaminaFull",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.CanEquip",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.ForceAim",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.Interior",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.IsWeakpoint",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.SafeGlide",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.StaminaConsume",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.StaminaRegenCd",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.VehicleActivate",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.VehicleRecharge",DevComment="")
+GameplayTagList=(Tag="GAS.Conditions.WalkOnly",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.ApplyAttributes",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.AttackHit",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.ChangeChar",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.DirectDamage",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.DragDrop",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.DropItem",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.HotBarSelect",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.Interact",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.NotifyDialogue",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.PickUpItem",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.QuickMove",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.SplitItem",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.Teleport",DevComment="")
+GameplayTagList=(Tag="GAS.PayloadEvents.TimeTravel",DevComment="")
+GameplayTagList=(Tag="Input.Crouch",DevComment="")
+GameplayTagList=(Tag="Input.Fire",DevComment="")
+GameplayTagList=(Tag="Input.Jump",DevComment="")
+GameplayTagList=(Tag="Input.Sprint",DevComment="")
+GameplayTagList=(Tag="Input.Super",DevComment="")
+GameplayTagList=(Tag="Inventory.Accessory",DevComment="")
+GameplayTagList=(Tag="Inventory.Equipment",DevComment="")
+GameplayTagList=(Tag="Minimap.Locations",DevComment="")
+GameplayTagList=(Tag="Minimap.Players",DevComment="")
+GameplayTagList=(Tag="Minimap.Teleports",DevComment="")
+GameplayTagList=(Tag="Sky.Weather.Rain",DevComment="")
+GameplayTagList=(Tag="Stencil.Interact",DevComment="")
+GameplayTagList=(Tag="Stencil.XraySkill",DevComment="")
+GameplayTagList=(Tag="Team.Cellien",DevComment="")
+GameplayTagList=(Tag="Team.Friends",DevComment="")

